title: Jader Lopez # your name (or website title) here
logo: "/images/ñññ.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Worker with experience in database manipulation and analysis. SQL skills, data cleaning and visualization.
  Committed to obtaining relevant information and supporting data-based decision making.
  
  <br><br>
   :-)
  <br><br>
  <a href="https://www.linkedin.com/in/jader-lopez-400355257/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
