title: Jader Lopez # your name (or website title) here
logo: "/images/" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data scientist con experiencia en la manipulacion de bases de datos como SQL, bases solidas en estadistica y conocimientos en programacion
  <br><br>
   :-)
  <br><br>
  <a href="https://www.linkedin.com/in/jader-lopez-400355257/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
