title: Jader Lopez # your name (or website title) here
logo: "/images/jader.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Worker con experiencia en manipulaci칩n y an치lisis de bases de datos. Habilidades en SQL, limpieza de datos y visualizaci칩n.
  Comprometido con obtener informaci칩n relevante y apoyar la toma de decisiones basadas en datos.
  <br><br>
   :-)
  <br><br>
  <a href="https://www.linkedin.com/in/jader-lopez-400355257/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
